# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello, world!
email: kkp7700@gmail.com
description: Statistical softwares or literature reviews for statistical genetics # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://statpng.github.io/TopicInPythonWebCrawling" # the base hostname & protocol for your site
author: Kipoong Kim

links:
  
theme: jekyll-theme-hacker